apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command: ['sh', '-c', 'echo hello; sleep 3600']
    image: busybox
    name: busybox1
  - command: ['sh', '-c', 'echo hello; sleep 3600']
    image: busybox
    name: busybox2
